services:
  kakao-webhook:
    image: ghcr.io/parkhyunchang/kakao_webhook:latest
    container_name: kakao_webhook
    restart: always
    ports:
      - "3500:3500"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "3306"
      DB_USER: hyunchang88
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: kakao_db
      LOG_DIR: /app/logs
      TZ: Asia/Seoul
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
